type TierType = {
  MAXIMUM_NUMBER_OF_PROJECTS: number;
  MAXIMUM_NUMBER_OF_TEXT_REVIEWS: number;
  MAXIMUM_NUMBER_OF_VIDEO_REVIEWS: number;
  PRICE_IN_CENTS: number;
};

export const FREE: TierType = {
  MAXIMUM_NUMBER_OF_PROJECTS: 1,
  MAXIMUM_NUMBER_OF_TEXT_REVIEWS: 25,
  MAXIMUM_NUMBER_OF_VIDEO_REVIEWS: 1,
  PRICE_IN_CENTS: 0,
};
export const PRO: TierType = {
  MAXIMUM_NUMBER_OF_PROJECTS: 3,
  MAXIMUM_NUMBER_OF_TEXT_REVIEWS: Infinity,
  MAXIMUM_NUMBER_OF_VIDEO_REVIEWS: 5,
  PRICE_IN_CENTS: 499,
};
